name: simple_secure_storage_workspace
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: '>=3.29.0'

workspace:
  - packages/simple_secure_storage
  - packages/simple_secure_storage_android
  - packages/simple_secure_storage_darwin
  - packages/simple_secure_storage_linux
  - packages/simple_secure_storage_platform_interface
  - packages/simple_secure_storage_web
  - packages/simple_secure_storage_windows
  - packages/simple_secure_storage/example

dev_dependencies:
  melos: ^7.0.0-dev.8
