name: simple_secure_storage
description: "Simple and secure storage for Flutter. Supports Android, iOS, macOS, Windows and web !"
version: 0.3.1
homepage: https://github.com/Skyost/SimpleSecureStorage
repository: https://github.com/Skyost/SimpleSecureStorage/tree/master/packages/simple_secure_storage
issue_tracker: https://github.com/Skyost/SimpleSecureStorage/issues
funding:
  - https://ko-fi.com/Skyost
  - https://paypal.me/Skyost

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  simple_secure_storage_platform_interface: ^0.2.0
  simple_secure_storage_android: ^0.2.1
  simple_secure_storage_darwin: ^0.2.0
  simple_secure_storage_windows: ^0.3.0
  simple_secure_storage_linux: ^0.2.0
  simple_secure_storage_web: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  melos: ^6.3.0

flutter:
  plugin:
    platforms:
      android:
        default_package: simple_secure_storage_android
      ios:
        default_package: simple_secure_storage_darwin
      macos:
        default_package: simple_secure_storage_darwin
      windows:
        default_package: simple_secure_storage_windows
      linux:
        default_package: simple_secure_storage_linux
      web:
        default_package: simple_secure_storage_web
