name: simple_secure_storage_platform_interface
description: Common platform interface for the Simple Secure Storage plugin.
homepage: https://github.com/Skyost/SimpleSecureStorage
repository: https://github.com/Skyost/SimpleSecureStorage/tree/master/packages/simple_secure_storage_platform_interface
issue_tracker: https://github.com/Skyost/SimpleSecureStorage/issues
version: 0.2.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ">=1.10.0 <2.0.0"
  plugin_platform_interface: ">=2.1.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^5.0.0
